### ISSUE TITLE
Use Redis ACL (user and password) to authentify with Redis 6

### ISSUE THREAD

**Issue by uiytt** [Simonsator/Party-API-For-Spigot#10]
Currently, there is no way (in contrary to RundisBungee) to connect to Redis using a user and a password (the ACL system of Redis 6).
This force to enable the default user (anonymous) and the old auth system of Redis 5. 
This could be a huge security issue for any server.

**Comment by Simonsator** [comment]
Added with commit [cf57dcd9fefd0c89b9a352464abc05adf7408b38](https://github.com/Simonsator/Party-API-For-Spigot/commit/cf57dcd9fefd0c89b9a352464abc05adf7408b38)
